### PR TITLE
Fix config file discovery on Windows

### PR DESCRIPTION
**Pull request by adrien1018**
Presumably solves #60 (at least tested on my own Windows 10 environment).

### CODE REVIEW

**Comment by vpj** [comment]
Thank @adrien1018 !

**Review by vpj — APPROVED** [review]

**Comment by xupeng1910** [comment]
hey, vpj,

Thanks for your new merge. That helps us too much to run our model on Windows. 
However, I suppose this problem is still on the distributed verion. I mean when I installed the labml by `pip install labml`, the problem for the Windows platform is still existing. Is it possilbe to distribute the new version labml on pip market? 

Best Regards,
Peng

**Comment by vpj** [comment]
@xupeng1910 ,

Updated the pip package with latest fixes by @adrien1018 

https://pypi.org/project/labml/0.4.120/

**Comment by xupeng1910** [comment]
@vpj Get it. Thanks

**Pull request merged**
