### PR TITLE
🐛 windows directory loop

### PR DESCRIPTION
**Pull request by nmasnadithya**

### CODE REVIEW

**Review by vpj — APPROVED** [review]

**Comment by shetsecure** [comment]
Thanks guys, this solves the infinite loop on Windows.

But the problem of running labml on a local jupyter notebook still persists, please see #60.

**Comment by nmasnadithya** [comment]
Glad this fixed your issue. We are still testing this to make sure this fix makes the library fully functional for all use cases under windows, before we release it to the public.

Let's discuss about your python notebook issue in the Github issue to make it easy for others to follow up on it.

**Comment by adrien1018** [comment]
It may be more idiomatic to use `str(path) == path.anchor` ([Path.anchor](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.anchor))

**Comment by vpj** [comment]
https://github.com/lab-ml/labml/pull/62 Fixes this in better way

**Pull request closed without merging**
